development_overrides:
  # run file-system backend for local development
  backend:
    name: file-system
    api_root: /api
  # reset 'editorial_workflow' if enabled, since it breaks in file-system mode
  # publish_mode: ''

# regular configuration
backend:
  name: github
  squash_merges: true
  repo: bjrn/gatsby-with-netlify-cms
  branch: master

display_url: https://gatsby-with-netlify-cms.netlify.com/
# publish_mode: editorial_workflow
media_folder: static/assets
public_folder: '/assets'

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: articles
    label: Articles
    description: 'Articles'
    folder: src/pages/
    slug: '{{slug}}'
    create: true
    extension: mdx
    format: frontmatter
    widget: mdx
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Body, name: body, widget: mdx }
