development_overrides:
  # run file-system backend for local development
  backend:
    name: file-system
    api_root: /api
  # reset 'editorial_workflow' if enabled, since it breaks in file-system mode
  # publish_mode: ''

# regular configuration
backend:
  name: github
  squash_merges: true
  repo: Ugrumiy/gatsby-starter2
  branch: master

display_url: https://gatsby-with-netlify-cms.netlify.com/
# publish_mode: editorial_workflow
media_folder: static/assets
public_folder: '/assets'

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'Settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'src/_data/globalSiteSettings/globalSiteSettings.yaml'
        description: 'General Site Settings'
        fields:
          - {label: Main Navigation Config, name: mainNavConfig, widget: list, fields: [{ label: 'Menu Item Title', name: 'title', widget: 'string' },{ label: 'Menu Item Href', name: 'href', widget: 'string' }]}
          - {
            label: Metadata,
            name: siteMetadata,
            widget: object,
            fields: [
            {
              label: Title,
              name: siteTitle,
              widget: string
            }, {
              label: Title Short,
              name: siteTitleShort,
              widget: text
            }, {
              label: Site Description,
              name: siteDescription,
              widget: text
            }, {
              label: Site Url,
              name: siteUrl,
              widget: text
            }, {
              label: Theme Color,
              name: themeColor,
              widget: text
            }
            ]
          }
  - name: models
    label: Models
    description: 'Model Pages'
    folder: src/_content/model
    slug: '{{slug}}'
    create: true
    extension: mdx
    format: frontmatter
    widget: mdx
    fields:
      - { label: "PageTemplate", name: "huggerTemplate", widget: "hidden", default: "default" }
      - { label: Filename, name: title, widget: string, required: true, hint: -- separator }
      - { label: Body, name: body, widget: mdx }
